apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: debug
  annotations:
    sidecar-injector-webhook.morven.me/inject: "true"
  labels:
    app: busybox
spec:
  containers:
    - name: sleep
      image: docker.io/library/busybox:latest
      command: ["/bin/sleep", "infinity"]
      imagePullPolicy: IfNotPresent